### ISSUE TITLE
precision and portability

### ISSUE THREAD

**Issue by pletzer** [jnga773/Cascade_Trajectory#1]
Hi @jnga773,

To make sure that the code can be ported to other compilers, we recommend not to use REAL(kind=8) to define real*8 (double precision) reals. Most compilers will map kind=8 to real*8 but the standard does not require it. 

Additionally, every real constant which is not an integer, e.g. 0.25, should have the kind attached to ensure that the constant is defined with the intended precision. This is done with appending _KIND, for instance _8 in your case (again it should be _r8 or whatever the real kind is).

Recommended changes
-------------------------

Use one fo the methods below:

Option 1. Remove (KIND=8) and compile with command line option -r8. Most compilers support this option. No other code change is required - the drawback is that not all compilers may have a -r8 option.

-or-

Option 2. Be explicit and define
integer, parameter :: r8 = selected_real_kind(12, 100)
real(kind=r8) :: ...
...                      0.25_r8

Option 2 is preferred when building a library that is intended to be used by many drivers. Because we're dealing with a standalone code, Option 1 is might be chosen.

**Comment by pletzer** [comment]
I've been looking at code on the web and I can see that real(kind=8) is now often used. So maybe ok to use kind=8 but all constant need to get _8. 

No need to add _8 for option 1.

**Comment by chrisdjscott** [comment]
If going with option 1, the command line option to default to double precision for ifort is `-r8` and for gfortran is `-fdefault-real-8`. The other advantage of that option is that it would be easy to switch between single and double precision to see if the results are acceptable with single precision. This option would result in the least changes to the source code too (delete `(KIND=8)` and change `DSQRT` to `SQRT`).

**Comment by pletzer** [comment]
Resolved.
